## Settings
title: CoopSec
owner: "root"
url: "https://coopsec.github.io/talk"
baseurl: "/talk"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
  headers:
    Access-Control-Allow-Origin: "*"
## Global Variables
email: ""
github: ""
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Designed by CoopSec, All Rights Reserved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "CoopSec CoopSec CoopSec"
theme: jekyll-theme-slate
