## Settings
title: pRoJEct-NeGYa
owner: "DeerRIDER"
url: "https://github.com/coopsec"
baseurl: "/talk"
permalink: /:title/
description: ""
markdown: kramdown
webrick:
headers:
Access-Control-Allow-Origin: "*"
## Global Variables
email: "root@coopsec.com"
github: "coopsec"
# path to: css/, fonts/, img/ and js/
assets_path: "/assets" # i.e. "/assets" 
statement: "Designed by CoopSec, All Rights Reserved"
# default max toc levels: 1 - 6 (h1 - h6)
toc_level: 3
# texts randomly displayed in background
bgtext: "Coop Security Coop Secuirty Coop Security"
